### PR TITLE
Custom states

### LINKED ISSUE #164: Custom oxidation state calls
Currently, if someone wants to use a custom set of oxidation states, they would need to rewrite part of the codebase in order to achieve this functionality. 
To make some SMACT functions more extensible to custom oxidation states lists, we should add a function to call custom oxidation states. An obvious area where this can be impactful is the `smact_filter` function where a user may want to use their own set of oxidation states to generate SMACT-plausible compositions. The user could either load in a set of oxidation states from a file (in which case we need to specify a file format for compatibility) or load from an object in memory (e.g. a dictionary, or a dataframe etc.).

### PR DESCRIPTION
**Pull request by AntObi**
# Custom oxidation states call

## Description

* Enable users to load in their oxidation states text file
* Allow `smact_filter` to use a custom oxidation state list
* Fixed line-length to 80 in pre-commit-config.yaml for `isort` and `black`

Fixes #164

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

- [x] Verified `smact_filter` works by passing an oxidation states text file to the `oxidation_states_set` argument

**Test Configuration**:
* Python version: 3.9
* Operating System: WSL2(Ubuntu)

## Reviewers

@keeeto I've added the feature you've requested. I want to check if you're happy with the implementation before I merge it into the master branch

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by mdi-group** [comment]
Hi @AntObi - I am just curious, where would one set the list of oxidation states to be used in a typical workflow?
For example in the [SolarOxides example](https://github.com/WMD-group/SMACT/blob/master/examples/Solar_oxides/SolarOxides.ipynb) where would I tell it to use a different set of oxidation states?

**Comment by AntObi** [comment]
> Hi @AntObi - I am just curious, where would one set the list of oxidation states to be used in a typical workflow? For example in the [SolarOxides example](https://github.com/WMD-group/SMACT/blob/master/examples/Solar_oxides/SolarOxides.ipynb) where would I tell it to use a different set of oxidation states?

Currently to use the other built-in oxidation states list, we can modify that example as follows:

Original oxidation states call:

```python
    # For each set of species (in oxidation states) apply both SMACT tests
    for ox_a, ox_b, ox_c in product(
        els[0].oxidation_states,
        els[1].oxidation_states,
        els[2].oxidation_states,
    ):
```

To use the built in icsd oxidation states:
```python
    # For each set of species (in oxidation states) apply both SMACT tests
    for ox_a, ox_b, ox_c in product(
        els[0].oxidation_states_icsd,
        els[1].oxidation_states_icsd,
        els[2].oxidation_states_icsd,
    ):
```

Using the pymatgen structure prediction oxidation states in this example:
```python
    # For each set of species (in oxidation states) apply both SMACT tests
    for ox_a, ox_b, ox_c in product(
        els[0].oxidation_states_sp,
        els[1].oxidation_states_sp,
        els[2].oxidation_states_sp,
    ):
```

I've originally made this pull request with the built-in `smact_filter` in mind, and a custom oxidation states file could be supplied to the `oxidation_states_set` argument.


If we want to have a similar API for making these calls, then I could make a new attribute for the `Element` class:
`Element.oxidation_states_custom`. For the examples above, we would access the attribute `el.oxidation_states_custom`. To implement this, the `Element` class can take an optional argument, let's call it `oxi_states_custom_filepath`, which will then set the property `oxidation_states_custom` to the oxidation states for that particular element based on the supplied file.

**Comment by mdi-group** [comment]
Thanks @AntObi - that is very clear. I understand now. I was struggling to see how this would be accessed. But I think that implementing in the `smact_filter` in the first instance is a sound decision. Code looks good and tests are passing. I think we can merge!

**Comment by AntObi** [comment]
Hi @keeeto, I've made some more changes:

The `Element` class now takes an optional argument of `oxi_states_custom_filepath` which allows a user to supply a text file containing oxidation states. Then the oxidation states can be accessed through the attribute `oxidation_states_custom`.

Example:

```python
import smact

Fe = smact.Element("Fe", oxi_states_custom_filepath = "/path/to/oxidation_states.txt")

print(Fe.oxidation_states_custom)
```
I've also updated the `element_dictionary` function to take the optional argument of `oxi_states_custom_filepath`. This should allow users to quickly create a list of `Element` objects which have access to the custom oxidation states.

So for the solar oxides example, you would apply the following changes:

Instead of 
```python
all_el = smact.element_dictionary()
```
You would create the dictionary of all elements with a supplied oxidation states text file:
 
```python
all_el = smact.element_dictionary(oxi_states_custom_filepath = "/path/to/oxidation_states.txt")
```

Then the oxidation states call in the smact_filter function defined in that particular example becomes:
```python   
 # For each set of species (in oxidation states) apply both SMACT tests
    for ox_a, ox_b, ox_c in product(
        els[0].oxidation_states.custom,
        els[1].oxidation_states.custom,
        els[2].oxidation_states.custom,
    ):
```

**Review by keeeto — APPROVED** [review]
All looks good to me!

**Pull request merged**
